# Generated by Django 5.2.14 on 2026-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20),
        ),
    ]
