# Generated by Django 5.2.14 on 2026-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20),
        ),
    ]
