# Generated by Django 5.2.14 on 2026-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_notes_appointmentdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Clínica Médica', 'Clínica Médica'), ('Pediatria', 'Pediatria'), ('Cirurgia Geral', 'Cirurgia Geral'), ('Ginecologia e Obstetrícia', 'Ginecologia e Obstetrícia'), ('Anestesiologia', 'Anestesiologia'), ('Cardiologia', 'Cardiologia'), ('Ortopedia e Traumatologia', 'Ortopedia e Traumatologia'), ('Medicina do Trabalho', 'Medicina do Trabalho'), ('Oftalmologia', 'Oftalmologia'), ('Radiologia e Diagnóstico por Imagem', 'Radiologia e Diagnóstico por Imagem'), ('Dermatologia', 'Dermatologia'), ('Psiquiatria', 'Psiquiatria'), ('Medicina de Família e Comunidade', 'Medicina de Família e Comunidade'), ('Neurologia', 'Neurologia'), ('Urologia', 'Urologia'), ('Otorrinolaringologia', 'Otorrinolaringologia'), ('Gastroenterologia', 'Gastroenterologia'), ('Endocrinologia e Metabologia', 'Endocrinologia e Metabologia'), ('Nefrologia', 'Nefrologia'), ('Pneumologia', 'Pneumologia')], max_length=120),
        ),
    ]
