# Generated by Django 5.2.14 on 2026-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctor_user_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
