# Generated by Django 5.2.14 on 2026-07-18 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctor_appointment_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_slots', to='core.doctor')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'weekday', 'start_time'), name='unique_weekly_slot')],
            },
        ),
    ]
