# Generated by Django 5.2.14 on 2026-07-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_weeklyslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='core.doctor')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.dateoverride')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='dateoverride',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='unique_date_override'),
        ),
        migrations.AddConstraint(
            model_name='dateslot',
            constraint=models.UniqueConstraint(fields=('override', 'start_time'), name='unique_date_slot'),
        ),
    ]
