from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("signup/", views.signup, name="signup"),
    path("signup/patient/", views.signup_patient, name="signup-patient"),
    path("signup/doctor/", views.signup_doctor, name="signup-doctor"),
    path("availability/", views.calendar, name="calendar"),
    path("availability/toggle/", views.calendar_toggle, name="calendar-toggle"),
    path("availability/duration/", views.calendar_duration, name="calendar-duration"),
    path("availability/month/", views.calendar_month, name="calendar-month"),
    path("availability/day/", views.calendar_day, name="calendar-day"),
    path("availability/day/customize/", views.calendar_day_customize, name="calendar-day-customize"),
    path("availability/day/toggle/", views.calendar_day_toggle, name="calendar-day-toggle"),
    path("availability/day/remove/", views.calendar_day_remove, name="calendar-day-remove"),
    path("guidance/", views.specialty_chat, name="specialty-chat"),
    path("guidance/send/", views.specialty_chat_send, name="specialty-chat-send"),
    path("guidance/reset/", views.specialty_chat_reset, name="specialty-chat-reset"),
    path("appointments/", views.list_appointments, name="appointment-list"),
    path("appointments/create/", views.create_appointment, name="appointment-create"),
    path("appointments/panel/", views.booking_panel, name="booking-panel"),
    path("appointments/day/", views.booking_day, name="booking-day"),
    path("appointments/<int:appointment_id>/update/", views.update_appointment, name="appointment-update"),
    path("appointments/<int:appointment_id>/delete/", views.delete_appointment, name="appointment-delete"),
    path("appointments/<int:appointment_id>/cancel/", views.cancel_appointment, name="appointment-cancel"),
    path("appointments/<int:appointment_id>/complete/", views.complete_appointment, name="appointment-complete"),
    path("appointments/<int:appointment_id>/start/", views.start_appointment, name="appointment-start"),
    path("appointments/<int:appointment_id>/attendance/", views.attendance, name="attendance"),
    path("appointments/<int:appointment_id>/attendance/notes/", views.attendance_notes, name="attendance-notes"),
    path("appointments/<int:appointment_id>/attendance/documents/", views.attendance_doc_add, name="attendance-doc-add"),
    path("appointments/documents/<int:document_id>/delete/", views.attendance_doc_delete, name="attendance-doc-delete"),
    path("appointments/<int:appointment_id>/attendance/transcribe/", views.attendance_transcribe, name="attendance-transcribe"),
    path("appointments/<int:appointment_id>/attendance/complete/", views.attendance_complete, name="attendance-complete"),
    path("patients/<int:patient_id>/history/", views.patient_history, name="patient-history"),
]
